### ISSUE TITLE
Issue when displaying image result 

### ISSUE THREAD

**Issue by rossman22590** [arscslvt/chat#1]
Ask for mock data graph of hello world image - it works but doesn't send to the website.

Error: Unknown message type.

![hello_world](https://github.com/arscslvt/chat/assets/6137292/e5f9abdb-e06f-48c3-b332-94132abe9f44)

![image](https://github.com/arscslvt/chat/assets/6137292/e776ea6d-aa0b-45b0-8c5b-07e3e884d0c3)

**Comment by arscslvt** [comment]
Hi @rossman22590 👋.
I didn't understand how did you get this hello-world image.

Can you please explain it to me step-by-step?

It will be great if you could send the thread URL where you asked for this.
