### ISSUE TITLE
Help modifying assistants id

### ISSUE THREAD

**Issue by aodrasa** [arscslvt/chat#2]
Love the UI and functionality of the app, I'm still fairly new to developing and having trouble customising my app with a different assistant id.

Would be great if you can direct me where I need to make those changes!

Thanks :)

**Comment by arscslvt** [comment]
Thank you so much! Really appreciated it. 🥰
I'll be glad to help you. You can text me on [Telegram](https://t.me/arscslvt) or Discord (@arscslvt) :)
