### ISSUE TITLE
Feature Request: The Voice  button

### ISSUE THREAD

**Issue by getofferhelp** [arscslvt/chat#3]
The Chat is really COOOOOL!
I like the UI so much, if the voice button could be activated, that would be Superstar of me~~~~

Would you like to add the edge tts to it @arscslvt , that voice solution looks convinent and strong.

**Comment by arscslvt** [comment]
**Thank you for you precious comment 🩷**

I'm actively developing the voice feature to enhance its functionality and user experience. I aim to make it more intelligent and engaging for users.

I'll activate it as soon as I can.

**Comment by getofferhelp** [comment]
Wow, that's great!

Looking forward to the feature : )
